### PR TITLE
add stm32h7 tim8 vector

### PR DESCRIPTION
**Pull request by CUAVcaijie**
add stm32h7 tim8 vector

### CODE REVIEW

**Comment by tridge** [comment]
this looks valid, why did you close?

**Comment by CUAVcaijie** [comment]
Half a month has passed, and nothing happens. I though it ’s a push problem, so I closed it.

**Comment by CUAVcaijie** [comment]
@tridge @lucasdemarchi @utzig @njoubert 
is it any problem with my merge request?

**Comment by njoubert** [comment]
Hi @CUAVcaijie! I don't think I can give you an informed opinion here. The formatting and style looks fine, whether its correct is probably a Tridge question! Thanks for the commit though!

**Comment by tridge** [comment]
my only concern about this is that TIM8 and TIM13 use the same interrupt vector. So if we try to use both TIM8 and TIM13 on the same board then I don't think it will work. We really should have something in the hwdef processing that checks for that sort of conflict.

**Pull request merged**
